### ISSUE TITLE
Feature Requests

### ISSUE THREAD

**Issue by maximusblade** [DraperStudio/Laravel-Friendable#1]
Nice to have: (for administrators)

- list all friendships (filter by: pending , approved, blocked etc)
- delete all friendships per user

**Comment by DraperStudio** [comment]
There are already the following methods:

- getFriendship
- getAllFriendships
- getPendingFriendships
- getAcceptedFriendships
- getDeniedFriendships
- getBlockedFriendships

To delete all friendships you should just list all friendships, iterate over them and call `unfriend` on each.
