### ISSUE TITLE
Why does the sender get the pending requests as well ?

### ISSUE THREAD

**Issue by minedun6** [DraperStudio/Laravel-Friendable#4]
I'm working on something that resembles facebook in the pending friends requests but the problem is that when i'm on the sender profile, i get the pending requests as well, so i was wondering, is there any way to exclude the sender from the recepients when trying to get the count ?
it's just a way to only show the number of pending requests to the recepient only ^^

**Comment by DraperStudio** [comment]
You could just select the friendships where the status is pending and the recipient id is the one of the current user if I understand you correctly.

**Comment by minedun6** [comment]
u already implemented one method like that called "getFriendRequests" and because i didn't pay any attention to read the class u amazingly did, i missed it and my bad.
