### ISSUE TITLE
Is there a way to access the other way of the relationship ?

### ISSUE THREAD

**Issue by minedun6** [DraperStudio/Laravel-Friendable#5]
I see there a function friends in the User model but is the other way around possible ?
I'm trying to make access to $friend->user ?

**Comment by DraperStudio** [comment]
You can call `$user->friends->first()->sender` or `$user->friends->first()->recipient` to get the entities that are involved in the relationship.

**Comment by minedun6** [comment]
No i'm try to access that throgh the view, and no i only have access to the friend model, i want the other way around

**Comment by DraperStudio** [comment]
I don't get what you are trying, the Friend Model is just a connection between two Entities which you can each access through the morphed sender or receiver.

**Comment by minedun6** [comment]
Yes I have access to the sender_id and receipient_id but the problem is that u have to make another access to the database to get the user associated to sender_id or the recepient_id

**Comment by DraperStudio** [comment]
Just call `Friend::find($whateverid)->sender` and `Friend::find($whateverid)-> recipient` and you will get the models for sender_* and receipient_* fields.
